# Generated by Django 4.2.23 on 2025-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="https://res.cloudinary.com/djreo8qmb/image/upload/v1757485348/default_qotzu0.png",
                upload_to="occavue_profile_images/",
            ),
        ),
    ]
