# Generated by Django 4.2.23 on 2025-09-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="media/occavue_profile_images/default_qotzu0",
                upload_to="occavue_profile_images/",
            ),
        ),
    ]
