# Generated by Django 4.2.23 on 2025-08-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="Unknown",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.category",
            ),
        ),
    ]
