# Generated by Django 4.2.23 on 2025-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_img_alter_event_category_eventimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="event_images/default.png",
                upload_to="occavue_images/",
            ),
        ),
    ]
